spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: admin
    url: jdbc:mysql://localhost:3306/fornecedor
    username: root
  jpa:
    hibernate:
      ddl-auto: update
